### ISSUE TITLE
String vs. `List Event` for PastEvents

### ISSUE THREAD

**Issue by rgrempel** [Pisys/elm-tapbox#1]
Very interesting module -- this fills a real need.

I'm curious about the use of a String to represent PastEvents, so that the programming model for dealing with PastEvents is to construct and apply regexes.

Did you consider making PastEvents a `List Event` instead? If you did that, then the `PastEvents -> Bool` functions would be list-processing code rather than regexes. Now, the logic would remain the same, but one would be iterating/matching over the list rather than using regexes.

Now, I can see that using regexes does have some advantages, since you can express certain kinds of conditions in a compact manner -- the equivalent code to express the equivalent conditions about a `List Event` would probably be longer. However, the list-oriented conditions would be easier to understand. Also, they would be typed in a way that the regexes aren't -- a little typo in the regex would often compile fine, whereas a similar error in a list-oriented condition could be a type error. And, the `Time` in the `List Event` would be an actual number that you could compute with directly, rather than a string.

I suppose with a `List Event` one would possibly want to write some 'helper' functions which were useful as the 'building blocks' for `PastEvents -> Bool` functions -- that is, functions which wrap up some of the typical work of iterating / matching the `List Events` so that the client code can be shorter.

Anyway, I was curious whether you had considered that approach.

**Comment by pisys** [comment]
Thanks for your question! 

The main problem with Lists is that they cannot be processed statefully in an easy way, while pattern matching means to keep a lot of state! I experimented with `List.foldl`, which is the only stateful iterating function (apart from `List.foldr` of course), but soon realized that I was actually reimplementing a kind of pattern matching which already exists with regex.

The question is which data structure reflects the "nature" of mouse/touch events best? What is their nature? They have a strict, non-changeable sequential order and most importantly are dependent on each other. 

I think a List does not reflect this nature. List applies best in the case of independent elements which might need to be mapped individually or re-ordered.

Surely a String is not exactly brilliant since it bypasses the compiler and Elm's automatic semantic versioning, ie. changes in the encoding format would demand a major release jump which cannot be enforced by Elm. It's a kind of a hack from the Elm perspective, I must confess.

However, the String representation better reflects the nature of events, I think, and is easier to handle.

**Comment by rgrempel** [comment]
I can see that working with `List Event` would mean implementing some pattern-matching helpers. I wonder whether there is anything in Haskell-world that could be adapted for your purposes. Perhaps `List` isn't the right type, actually -- it is a simple type, after all.

I don't know enough Haskell to know whether there is something out there that could be adapted to this purpose, but it feels as though there ought to be.

**Comment by pisys** [comment]
I've just made a new release. It now uses `List Event` instead of `String`. I've realized that pattern matching with lists actually works like a charm in Elm (no need for `foldl`).
